// ===========================
// 題材: 元素記号クイズ（118 元素）
// 元素記号・英語名: IUPAC Periodic Table of the Elements（2022-05-04 版。名前は 2016-11-28 に 113・115・117・118 番が決まってから変わっていない）
// 日本語名: 日本化学会 原子量専門委員会「原子量表（2026）」の元素名（113・115・117・118 番の日本語名は日本化学会 命名法専門委員会が 2016 年に決定）
// 漢字の元素名のよみ（すいそ など）は、コトバンク（デジタル大辞泉ほか）で確かめた。出典と確認日は constants.js の genso
// 行: [原子番号, 記号, 日本語名, 漢字を含む名前のよみ（カタカナだけの名前は null）, 英語名（IUPAC）]
// ===========================
(function (root) {
  'use strict';

  var ROWS = [
    [1, 'H', '水素', 'すいそ', 'hydrogen'],
    [2, 'He', 'ヘリウム', null, 'helium'],
    [3, 'Li', 'リチウム', null, 'lithium'],
    [4, 'Be', 'ベリリウム', null, 'beryllium'],
    [5, 'B', 'ホウ素', 'ほうそ', 'boron'],
    [6, 'C', '炭素', 'たんそ', 'carbon'],
    [7, 'N', '窒素', 'ちっそ', 'nitrogen'],
    [8, 'O', '酸素', 'さんそ', 'oxygen'],
    [9, 'F', 'フッ素', 'ふっそ', 'fluorine'],
    [10, 'Ne', 'ネオン', null, 'neon'],
    [11, 'Na', 'ナトリウム', null, 'sodium'],
    [12, 'Mg', 'マグネシウム', null, 'magnesium'],
    [13, 'Al', 'アルミニウム', null, 'aluminium'],
    [14, 'Si', 'ケイ素', 'けいそ', 'silicon'],
    [15, 'P', 'リン', null, 'phosphorus'],
    [16, 'S', '硫黄', 'いおう', 'sulfur'],
    [17, 'Cl', '塩素', 'えんそ', 'chlorine'],
    [18, 'Ar', 'アルゴン', null, 'argon'],
    [19, 'K', 'カリウム', null, 'potassium'],
    [20, 'Ca', 'カルシウム', null, 'calcium'],
    [21, 'Sc', 'スカンジウム', null, 'scandium'],
    [22, 'Ti', 'チタン', null, 'titanium'],
    [23, 'V', 'バナジウム', null, 'vanadium'],
    [24, 'Cr', 'クロム', null, 'chromium'],
    [25, 'Mn', 'マンガン', null, 'manganese'],
    [26, 'Fe', '鉄', 'てつ', 'iron'],
    [27, 'Co', 'コバルト', null, 'cobalt'],
    [28, 'Ni', 'ニッケル', null, 'nickel'],
    [29, 'Cu', '銅', 'どう', 'copper'],
    [30, 'Zn', '亜鉛', 'あえん', 'zinc'],
    [31, 'Ga', 'ガリウム', null, 'gallium'],
    [32, 'Ge', 'ゲルマニウム', null, 'germanium'],
    [33, 'As', 'ヒ素', 'ひそ', 'arsenic'],
    [34, 'Se', 'セレン', null, 'selenium'],
    [35, 'Br', '臭素', 'しゅうそ', 'bromine'],
    [36, 'Kr', 'クリプトン', null, 'krypton'],
    [37, 'Rb', 'ルビジウム', null, 'rubidium'],
    [38, 'Sr', 'ストロンチウム', null, 'strontium'],
    [39, 'Y', 'イットリウム', null, 'yttrium'],
    [40, 'Zr', 'ジルコニウム', null, 'zirconium'],
    [41, 'Nb', 'ニオブ', null, 'niobium'],
    [42, 'Mo', 'モリブデン', null, 'molybdenum'],
    [43, 'Tc', 'テクネチウム', null, 'technetium'],
    [44, 'Ru', 'ルテニウム', null, 'ruthenium'],
    [45, 'Rh', 'ロジウム', null, 'rhodium'],
    [46, 'Pd', 'パラジウム', null, 'palladium'],
    [47, 'Ag', '銀', 'ぎん', 'silver'],
    [48, 'Cd', 'カドミウム', null, 'cadmium'],
    [49, 'In', 'インジウム', null, 'indium'],
    [50, 'Sn', 'スズ', null, 'tin'],
    [51, 'Sb', 'アンチモン', null, 'antimony'],
    [52, 'Te', 'テルル', null, 'tellurium'],
    [53, 'I', 'ヨウ素', 'ようそ', 'iodine'],
    [54, 'Xe', 'キセノン', null, 'xenon'],
    [55, 'Cs', 'セシウム', null, 'caesium'],
    [56, 'Ba', 'バリウム', null, 'barium'],
    [57, 'La', 'ランタン', null, 'lanthanum'],
    [58, 'Ce', 'セリウム', null, 'cerium'],
    [59, 'Pr', 'プラセオジム', null, 'praseodymium'],
    [60, 'Nd', 'ネオジム', null, 'neodymium'],
    [61, 'Pm', 'プロメチウム', null, 'promethium'],
    [62, 'Sm', 'サマリウム', null, 'samarium'],
    [63, 'Eu', 'ユウロピウム', null, 'europium'],
    [64, 'Gd', 'ガドリニウム', null, 'gadolinium'],
    [65, 'Tb', 'テルビウム', null, 'terbium'],
    [66, 'Dy', 'ジスプロシウム', null, 'dysprosium'],
    [67, 'Ho', 'ホルミウム', null, 'holmium'],
    [68, 'Er', 'エルビウム', null, 'erbium'],
    [69, 'Tm', 'ツリウム', null, 'thulium'],
    [70, 'Yb', 'イッテルビウム', null, 'ytterbium'],
    [71, 'Lu', 'ルテチウム', null, 'lutetium'],
    [72, 'Hf', 'ハフニウム', null, 'hafnium'],
    [73, 'Ta', 'タンタル', null, 'tantalum'],
    [74, 'W', 'タングステン', null, 'tungsten'],
    [75, 'Re', 'レニウム', null, 'rhenium'],
    [76, 'Os', 'オスミウム', null, 'osmium'],
    [77, 'Ir', 'イリジウム', null, 'iridium'],
    [78, 'Pt', '白金', 'はっきん', 'platinum'],
    [79, 'Au', '金', 'きん', 'gold'],
    [80, 'Hg', '水銀', 'すいぎん', 'mercury'],
    [81, 'Tl', 'タリウム', null, 'thallium'],
    [82, 'Pb', '鉛', 'なまり', 'lead'],
    [83, 'Bi', 'ビスマス', null, 'bismuth'],
    [84, 'Po', 'ポロニウム', null, 'polonium'],
    [85, 'At', 'アスタチン', null, 'astatine'],
    [86, 'Rn', 'ラドン', null, 'radon'],
    [87, 'Fr', 'フランシウム', null, 'francium'],
    [88, 'Ra', 'ラジウム', null, 'radium'],
    [89, 'Ac', 'アクチニウム', null, 'actinium'],
    [90, 'Th', 'トリウム', null, 'thorium'],
    [91, 'Pa', 'プロトアクチニウム', null, 'protactinium'],
    [92, 'U', 'ウラン', null, 'uranium'],
    [93, 'Np', 'ネプツニウム', null, 'neptunium'],
    [94, 'Pu', 'プルトニウム', null, 'plutonium'],
    [95, 'Am', 'アメリシウム', null, 'americium'],
    [96, 'Cm', 'キュリウム', null, 'curium'],
    [97, 'Bk', 'バークリウム', null, 'berkelium'],
    [98, 'Cf', 'カリホルニウム', null, 'californium'],
    [99, 'Es', 'アインスタイニウム', null, 'einsteinium'],
    [100, 'Fm', 'フェルミウム', null, 'fermium'],
    [101, 'Md', 'メンデレビウム', null, 'mendelevium'],
    [102, 'No', 'ノーベリウム', null, 'nobelium'],
    [103, 'Lr', 'ローレンシウム', null, 'lawrencium'],
    [104, 'Rf', 'ラザホージウム', null, 'rutherfordium'],
    [105, 'Db', 'ドブニウム', null, 'dubnium'],
    [106, 'Sg', 'シーボーギウム', null, 'seaborgium'],
    [107, 'Bh', 'ボーリウム', null, 'bohrium'],
    [108, 'Hs', 'ハッシウム', null, 'hassium'],
    [109, 'Mt', 'マイトネリウム', null, 'meitnerium'],
    [110, 'Ds', 'ダームスタチウム', null, 'darmstadtium'],
    [111, 'Rg', 'レントゲニウム', null, 'roentgenium'],
    [112, 'Cn', 'コペルニシウム', null, 'copernicium'],
    [113, 'Nh', 'ニホニウム', null, 'nihonium'],
    [114, 'Fl', 'フレロビウム', null, 'flerovium'],
    [115, 'Mc', 'モスコビウム', null, 'moscovium'],
    [116, 'Lv', 'リバモリウム', null, 'livermorium'],
    [117, 'Ts', 'テネシン', null, 'tennessine'],
    [118, 'Og', 'オガネソン', null, 'oganesson'],
  ];

  var items = ROWS.map(function (r) {
    return { id: String(r[0]), n: r[0], sym: r[1], ja: r[2], yomi: r[3], en: r[4] };
  });
  function names(it) { return it.yomi ? [it.ja, it.yomi] : [it.ja]; }

  var topic = {
    id: 'genso',
    // ページ（tools/build-pages.mjs が genso/index.html を作る）
    page: {
      title: '元素記号クイズ 118｜4択・入力・一覧・印刷',
      h1: '元素記号クイズ（118）',
      lead: '元素記号と名前を4択か入力で。1〜20番から118番まで。',
      description: '元素記号クイズ。1〜20番・36番まで・118すべてを、4択か入力（タイピング）の一問一答で。一覧で覚える・問題と答えを印刷もできる。登録不要・無料。',
      hub: '1〜20番から118番まで。名前→記号、記号→名前、原子番号→名前',
      icon: '⚗️',
      order: 1,
      note: '日本語名は日本化学会の原子量表の表記です。漢字の名前は、ひらがなのよみでも正解になります。',
    },
    unit: '元素',
    order: function (it) { return it.n; },
    label: function (it) { return it.n + ' ' + it.sym + ' ' + it.ja; },
    items: items,
    kinds: [
      {
        key: 'sym', label: '名前 → 記号', caseSensitive: true, inputHint: '記号を英字で（大文字・小文字を区別）',
        prompt: function (it) { return '「' + it.ja + '」の元素記号は？'; },
        answer: function (it) { return it.sym; },
        accept: function (it) { return [it.sym]; },
        choice: function (it) { return it.sym; },
      },
      {
        key: 'name', label: '記号 → 名前', inputHint: '名前を（ひらがな・カタカナどちらでも）',
        prompt: function (it) { return '元素記号「' + it.sym + '」の元素は？'; },
        answer: function (it) { return it.ja; },
        accept: names,
        choice: function (it) { return it.ja; },
      },
      {
        key: 'num', label: '原子番号 → 名前', inputHint: '名前を（ひらがな・カタカナどちらでも）',
        prompt: function (it) { return '原子番号 ' + it.n + ' の元素は？'; },
        answer: function (it) { return it.ja; },
        accept: names,
        choice: function (it) { return it.ja; },
      },
    ],
    filters: [
      {
        key: 'range', label: '範囲', def: '20',
        options: [
          { v: '20', label: '1〜20番', test: function (it) { return it.n <= 20; } },
          { v: '36', label: '1〜36番', test: function (it) { return it.n <= 36; } },
          { v: '54', label: '1〜54番', test: function (it) { return it.n <= 54; } },
          { v: 'all', label: '118 すべて', test: function () { return true; } },
        ],
      },
    ],
    columns: [
      { label: '番号', get: function (it) { return it.n; } },
      { label: '記号', get: function (it) { return it.sym; }, hide: true },
      { label: '名前', get: function (it) { return it.ja + (it.yomi ? '（' + it.yomi + '）' : ''); }, hide: true },
      { label: '英語名', get: function (it) { return it.en; } },
    ],
    explain: function (it) { return '原子番号 ' + it.n + '　' + it.sym + '　' + it.ja + (it.yomi ? '（' + it.yomi + '）' : '') + '　英語名 ' + it.en; },
    link: function () { return null; },
    sourceKey: 'genso',
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = topic;
  else { root.QuizTopics = root.QuizTopics || {}; root.QuizTopics[topic.id] = topic; }
})(this);
